#pragma once

#include <tonc.h>
#include <tonc_types.h>

// This file is autogenerated from the file in the graphics folder
#include "metr.h"

//#include "input.h"
#include "game.h"

// the input and output of the render() function
typedef struct RENDERSTATE {
    OBJ_ATTR *metroid; // temp, for demo
} RENDERSTATE;

int renderinit(RENDERSTATE* renderstate);

int render(INPUTSTATE* inputstate, GAMESTATE* gamestate, RENDERSTATE* renderstate);